trigger:
- master

variables:
- group: my-variables
- name: version
  value: 1.0.$(Build.BuildId)


pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
  
- task: FileTransform@1
  inputs:
    folderPath: $(System.DefaultWorkingDirectory)
    targetFiles: manifest-dev.json

- script: |
    npm install
    npx tfx-cli extension publish --manifest-globs manifest-dev.json --share-with staff0rd --token $(visualstudio-marketplace-pat)

  displayName: 'npm install and publish to dev'
