trigger:
- master

variables:
- group: my-variables
- name: version
  value: $(Build.BuildNumber)
- name: version.major
  value: 1
- name: version.minor
  value: 1
- name: version.patch
  value: $(Build.BuildId)

name: $(version.major).$(version.minor)$(Rev:.r)

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: FileTransform@1
  inputs:
    folderPath: $(System.DefaultWorkingDirectory)
    fileType: json
    targetFiles: | 
      manifest-dev.json
      cloudflarePurge/task.json

- script: |
    cat cloudflarePurge/task.json
    npm install
    npx tfx-cli extension publish --manifest-globs manifest-dev.json --share-with staff0rd --token $(visualstudio-marketplace-pat)

  displayName: 'npm install and publish to dev'
