trigger:
- master

variables:
- group: my-variables
- name: major
  value: 1
- name: minor
  value: 1
- name: patch
  value: $(Build.BuildId)
- name: version
  value: $(Build.BuildNumber)
- name: tfx-cloudflare-purge-id
  value: $(tfx-cloudflare-purge-dev-id)
- name: tfx-cloudflare-purge-name
  value: Purge Cache for Cloudflare (Development)

name: $(major).$(minor)$(Rev:.r)

pool:s
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens'
  inputs:
    targetFiles: | 
      manifest-dev.json
      cloudflarePurge/task.json

- script: |
    npm install
    npx tfx-cli extension publish --manifest-globs manifest-dev.json --share-with staff0rd --token $(visualstudio-marketplace-pat)

  displayName: 'npm install and publish to dev'
