trigger:
- master

variables:
- group: my-variables
- name: majorToken
  value: 1
- name: minorToken
  value: 1
- name: patchToken
  value: $(Build.BuildId)
- name: versionToken
  value: $(Build.BuildNumber)

name: $(majorToken).$(minorToken)$(Rev:.r)

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens'
  inputs:
    targetFiles: | 
      manifest-dev.json
      cloudflarePurge/task.json

- script: |
    cat cloudflarePurge/task.json
    cat manifest-dev.json
    # npm install
    # npx tfx-cli extension publish --manifest-globs manifest-dev.json --share-with staff0rd --token $(visualstudio-marketplace-pat)

  displayName: 'npm install and publish to dev'
